### ISSUE TITLE
指令信息合并与指令名建议

### ISSUE THREAD

**Issue by axlmly** [Alin-sky/koishi-plugin-ba-plugin#10]
能否将帮助信息里的ba指令整合进一个指令里，每次help的时候都会出现排版问题。

还有这指令别名也太多了吧

**Comment by Mulsd** [comment]
有没有更具体的例子？比如哪几个指令应该合并，help哪里有排班问题

**Comment by axlmly** [comment]
![b439a1c86ea6d2a80a11c33c91f7c82e](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/41771421/02ee577e-08a8-4afb-a408-71107707c6cb)
我觉得属于ba插件的所有指令都像kbot指令一样集合
![4e087ea4715b1c2da6d070ca806c52c2](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/41771421/fab022ae-3609-4924-bd83-3b51a329a103)

**Comment by Mulsd** [comment]
基于开发者的热烈讨论，我们暂时不考虑对这些指令进行合并。理由有：
- 会导致参数类指令过长。例如说整合之后，抽up池卡就是 ba.抽卡.up 日服 十连
- 每一个分开的插件都是不同的开发者开发的，指令分离可以防止因为某个分支功能出bug影响到其他开发者的指令工作。

后续代码成熟后，我们会对其进行优化
希望你能理解，感谢你的建议

**Comment by Alin-sky** [comment]
未来有时间全面重构1.0版本可以尝试整合下。现在我技术力还不足。目前已有的计划是将攒钻。升级和羁绊等计算功能整合在一改指令

之后的0.9.7版本会减少攻略系统的别名。

感谢建议
