### ISSUE TITLE
卡池查询获取不到图片报错

### ISSUE THREAD

**Issue by fmd12345** [Alin-sky/koishi-plugin-ba-plugin#11]
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/5960842/3cd72bb0-2c4f-4e39-946f-45c75a85206d)
看了一眼日志，发现url的括号不对
日志里的括号是英文括号
实际的括号是中文括号
http://124.221.99.85:8088/stuimg/assets/Student/真白（泳装）.png
http://124.221.99.85:8088/stuimg/assets/Student/真白(泳装).png

**Comment by Alin-sky** [comment]
这个bug是最近进行新抽卡系统测试时，将图源服务器的括号由全角改半角导致的
目前已经同时添加了全角和半角的学生头像图片文件
感谢反馈
