### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by kurimixueying** [Alin-sky/koishi-plugin-ba-plugin#13]
![Screenshot_2023-11-29-19-04-48-381_cn anillc koishi](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/152382363/785041d4-b5ba-4787-a4ab-4cae430db8a0)
![Screenshot_2023-11-29-19-05-09-113_cn anillc koishi](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/152382363/de2edcd8-da0f-47e0-9357-09061a9ee567)
请问这是什么问题

**Comment by Alin-sky** [comment]
koishi的沙盒无法显示本地文件的图片

**Comment by Alin-sky** [comment]
https://forum.koishi.xyz/t/topic/1721
