### ISSUE TITLE
插件异常报错

### ISSUE THREAD

**Issue by Starrain08** [Alin-sky/koishi-plugin-ba-plugin#15]
插件异常报错
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/119772101/d5564c7f-c7a5-4f86-8603-cce20338ac56)
koishi更新至4.17.6后出现此问题
使用设备系统为Windows11家庭版

**Comment by Alin-sky** [comment]
这个应该是koishi的一个警告，不影响使用，后继1.1.0会尝试修复
