### ISSUE TITLE
插件下载问题

### ISSUE THREAD

**Issue by Starrain08** [Alin-sky/koishi-plugin-ba-plugin#16]
插件一直无法获取一个json文件，本地不存在这个文件

![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/119772101/ad488061-7606-478a-8916-642928706fbc)

**Comment by Alin-sky** [comment]
已调整云json，重启插件后应该不会提示了，缺失这个文件不影响使用，感谢反馈😽
