### ISSUE TITLE
插件时常无反应

### ISSUE THREAD

**Issue by Starrain08** [Alin-sky/koishi-plugin-ba-plugin#17]
koishi在运行一段时间后，发送指令ba插件无反应，其他插件正常工作，重启后情况消失
重启后插件配置界面命令不显示，等待加载完后重载commands插件依旧不显示，需要多次重载
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5625U with Radeon Graphics         

Binaries:
    Node: 20.12.2
    Yarn: 4.0.1

Koishi:
    Core: 4.17.6
    Console: 5.28.4
    Koishi Desktop: 1.1.2

**Comment by shangxueink** [comment]
给出具体的复现条件和报错，这样开发者才能处理。

根据实际测试，我无法复现你描述的这种情况，所以我们无法定位问题。

加上这样模棱两可的描述，我们不能断定这是ba-plugin插件的问题。

**Comment by Starrain08** [comment]
> 给出具体的复现条件和报错，这样开发者才能处理。
> 
> 根据实际测试，我无法复现你描述的这种情况，所以我们无法定位问题。
> 
> 加上这样模棱两可的描述，我们不能断定这是ba-plugin插件的问题。

报错日志根本没有，找遍了koishi这边，插件这里有没有什么debug模式，我好再次复现

**Comment by Starrain08** [comment]
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/119772101/a636d464-b858-45f9-9a09-fe603c6a8b05)

**Comment by Starrain08** [comment]
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/119772101/21d4150f-707c-41b9-86f6-a631fb6801cd)

**Comment by Starrain08** [comment]
这会出现错误日志了
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/119772101/01c0becc-877b-406f-8ee3-0ea9f556e675)
