### ISSUE TITLE
插件加载bug

### ISSUE THREAD

**Issue by Starrain08** [Alin-sky/koishi-plugin-ba-plugin#19]
更新至最新后，插件报错，且大部分指令消失
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/119772101/5938397e-19f7-4397-a968-fba43f80d315)
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/119772101/0fea35ee-c15f-4da9-907c-ecde8845a338)

**Comment by Alin-sky** [comment]
已找到问题，b3版本应该已修复，感谢反馈
如果在使用上有什么问题和bug反馈，可以添加koishi的非官方交流群（590104798），在群里@我或上学，可以更快的反馈和解决问题
