### ISSUE TITLE
攻略待添加

### ISSUE THREAD

**Issue by Alin-sky** [Alin-sky/koishi-plugin-ba-plugin#2]

**Comment by Alin-sky** [comment]
待补充类似arona的推图导航

**Comment by diyigemt** [comment]
来来来
https://doc.arona.diyigemt.com/api/

**Comment by Alin-sky** [comment]
> 来来来
> 
> https://doc.arona.diyigemt.com/api/
万分感谢巨佬提供公开的API服务🙏🙏
