### ISSUE TITLE
QQBot发不出图（群）

### ISSUE THREAD

**Issue by QingFu231** [Alin-sky/koishi-plugin-ba-plugin#20]
QQBot发不出图（群）
![e24d7152662defb188ec86d9ce506dd6](https://github.com/user-attachments/assets/4bae5bdc-477a-43bb-abf7-fe0c190fc8f0)
这是日志
![f732d33642512defc3008e8b2c62de4b](https://github.com/user-attachments/assets/8714f99d-f3a9-4832-bf3e-5c8d50ddd382)
我是第一次用koishi框架，请指导，谢谢

**Comment by QingFu231** [comment]
抽漫画，关卡，可以发出来![image](https://github.com/user-attachments/assets/cb13afca-13dd-46d6-9d9d-2c3cca7ed27d)

**Comment by QingFu231** [comment]
![image](https://github.com/user-attachments/assets/9c7d2875-8507-4d03-a7f8-0da208ec46eb)
![image](https://github.com/user-attachments/assets/6963210f-362d-4767-b66a-b9f5e20fb5cd)

**Comment by shangxueink** [comment]
---

## 问题描述

在使用其他插件时，我们偶尔也会遇到类似情况，因此不能确定是否是 `ba-plugin` 的个例问题。目前报错 `bad request` 还没有找到稳定的复现条件，但在较高并发的情况下比较容易出现。

至于抽取漫画是正常的，因为漫画并非从本地渲染后发送，而是从 `.\data\bap-json\manga_main.json` 中读取图片网络链接直接发送的，例如 `https://cdnimg.gamekee.com/wiki2.0/images/w_770/h_1080/829/43637/2023/6/5/926654.png`，这自然不会出现 `bad request` 问题。

## 日志分析

对于你提供的最后一张日志截图，我们注意到出现 `fetch c:\....\bap-img/background.png failed` 可能是因为你的资源并未下载完整。请确保插件的 `plugin_config.auto_update` 配置项是开启的，并且观察日志输出，直到资源下载完整。

## 我们的解决方案

在 1.2.0 版本中，我们将使用 `pathToFileURL` 函数，以进一步避免 `fetch` 错误，但这并不能确保 `bad request` 问题得到解决。

## 渲染器选择

除了确保资源下载完整外，还需要选择正确的渲染器。我们推荐使用 `canvas` 而非 `puppeteer` 以加快响应速度。

---

**Comment by QingFu231** [comment]
您好，很抱歉打扰到您了，按您推荐的渲染器选择，渲染的却快了许多，资源也重新下载了一次，相关攻略图（/攻略 水大叔）可以发出来了。
您在 ’日志分析‘ 中指出 ’plugin_config.auto_update‘ 这个选项要开启，我去查看的时候该项是开启的状态，我注意到 ’fetch c:\....\bap-img/background.png failed‘这项报错有一个地方有点问题，它与我接触到的不同，如图这条斜杠应该为'\'而日志中的这条斜杠为’/‘，我在此目录下发现，’background.png‘是存在的，我在想是不是开发者不小心用错了而导致的问题，感谢您的回复。
![image](https://github.com/user-attachments/assets/3dc3833d-9d66-49c8-b5e3-adcb737a3e4f)
![image](https://github.com/user-attachments/assets/70fd838e-8954-439b-8aaa-80a76d3a5dea)

**Comment by shangxueink** [comment]
> 如图这条斜杠应该为''而日志中的这条斜杠为’/‘，我在此目录下发现，’background.png‘是存在的，我在想是不是开发者不小心用错了而导致的问题

实际上不是的，应该是没有使用同一的函数生成出来，
就像是手搓的一样，对ba-plugin来说是可以跑的

---

如果你还有什么疑问，请务必加入我们的QQ群聊讨论！972180367   [点击链接加入群聊【爱丽丝赞助者反馈群】：](https://qm.qq.com/q/opb7RrsWje)

也欢迎来监督插件开发的进度！
