### ISSUE TITLE
合并消息无法打开

### ISSUE THREAD

**Issue by Alirea10** [Alin-sky/koishi-plugin-ba-plugin#5]
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/111880868/c9919aee-0c87-4c9f-86cc-3c0ebb6ef1e2)
无报错，可能和发送格式有关。
沙盒内似乎可以分段发送
![image](https://github.com/Alin-sky/koishi-plugin-ba-plugin/assets/111880868/a7f7ff66-643f-46af-82d9-46692010a1f6)

**Comment by Alin-sky** [comment]
> 

感谢大佬反馈问题，阿林尝试修复

**Comment by Alin-sky** [comment]
0.8版本的模拟图式抽卡模拟器解决了问题（直接废弃旧抽卡模拟器）
